### ISSUE TITLE
Derive public key from private key for ed25519

### ISSUE THREAD

**Issue by mattcollier** [digitalbazaar/ed25519-verification-key-2018#6]
There is math and possibly existing helpers to do this computation: https://bitcoin.stackexchange.com/a/62351

The referenced function does exist in libsodium, but there is no explanation relating to how it can be used for this purpose.  Of course there would need to be a js implementation as well.  Maybe what is needed is here? https://github.com/dchest/tweetnacl-js/blob/master/README.md#scalar-multiplication

For use cases involving acceptance of end-user supplied key material, it would be nice to just accept private key which would reduce error rate.

**Comment by dlongley** [comment]
Closing as stale / addressed.
