### ISSUE TITLE
Compare buffers directly, do not convert to strings just to compare them

### ISSUE THREAD

**Issue by dlongley** [digitalbazaar/ed25519-verification-key-2018#9]
If we've got buffers to compare we should compare them directly rather than spending effort encoding them to strings just to compare them:

https://github.com/digitalbazaar/ed25519-verification-key-2018/blob/master/src/Ed25519VerificationKey2018.js#L315

**Comment by dmitrizagidulin** [comment]
@dlongley do you have a preferred comparison mechanism? Iterate through the bytes, that sort of thing?

**Comment by mattcollier** [comment]
I believe this is the preferred method: https://nodejs.org/docs/latest-v14.x/api/buffer.html#buffer_buf_compare_target_targetstart_targetend_sourcestart_sourceend

**Comment by dlongley** [comment]
@dmitrizagidulin,

> do you have a preferred comparison mechanism? Iterate through the bytes, that sort of thing?

Yeah, I believe that's the only isomorphic method. Compare length and then iterate through and compare bytes.

**Comment by JSAssassin** [comment]
Closing, implemented https://github.com/digitalbazaar/ed25519-verification-key-2018/pull/10
